use_frameworks!

platform :ios, '8.0'

target 'TabScrollViewContollerManager_Example' do
  pod 'TabScrollViewContollerManager', :path => '../'

  target 'TabScrollViewContollerManager_Tests' do
    inherit! :search_paths

    
  end
end
